name: buildabrain
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:


    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  qrscan: ^0.2.17
  cupertino_icons: ^0.1.2
  carousel_slider: 2.2.1
  calendar_strip: ^1.0.4
  animated_splash: ^1.0.0
  intl:
  flutter_widget_gallery: ^0.1.2
  image_picker:
  gallery_saver:
  percent_indicator: 2.1.1+1
  firebase_database:
  firebase_auth: ^0.11.1+8
  google_sign_in:
  firebase_storage:
  flutter_downloader: ^1.4.0
  cloud_firestore: ^0.13.4+1
  image_cropper:
  path_provider:
  flutter_cache_manager:
  collection:
  table_calendar: 2.2.3
  dio:
  basic_utils: ^2.5.3
  network_to_file_image:
  url_launcher: ^5.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: Balsamiq
      fonts:
        - asset: fonts/Balsamiq_Sans/BalsamiqSans-Bold.ttf
        - asset: fonts/Balsamiq_Sans/BalsamiqSans-BoldItalic.ttf
        - asset: fonts/Balsamiq_Sans/BalsamiqSans-Italic.ttf
        - asset: fonts/Balsamiq_Sans/BalsamiqSans-Regular.ttf




  assets:
    - lib/Assets/iq.png
    - lib/Assets/mindmap.png
    - lib/Assets/conversation.png
    - lib/Assets/hand.png
    - lib/Assets/qrcode.png
    - lib/Assets/bdblogo.jpg
    - lib/Assets/jungle.jpg
    - lib/Assets/face.jpg
    - lib/Assets/upper.png
    - lib/Assets/lower.jpg
    - lib/Assets/skeleton.jpg
    - lib/Assets/bodyparts.png
    - lib/Assets/qr.png
    - lib/Assets/chart.png
    - lib/Assets/googleIcon.png
    - lib/Assets/facebook.png
    - lib/Assets/teacher.png
    - lib/Assets/house.png
    - lib/Assets/leader.png
    - lib/Assets/noChildren.png
    - lib/Assets/defaultPro.jpg
    - lib/Assets/preschool.png
    - lib/Assets/junior.png
    - lib/Assets/advanced.png
    - lib/Assets/art.png
    - lib/Assets/science.png
    - lib/Assets/home.png
    - lib/Assets/schedule.png
    - lib/Assets/settings.png
    - lib/Assets/notify.png



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
